### ISSUE TITLE
`project down` returns an error

### ISSUE THREAD

**Issue by VictorMovileanu** [unikubehq/cli#36] opened 2021-06-14 14:16 UTC
previous commands were probably:
* unikube project up
* unikube deck install

```
victor@victor-ThinkPad-T490s:~/PycharmProjects/unikube-projects-service$ unikube project down
[DEBUG] {'message': 'This project cannot be retrieved.', 'path': ['project'], 'extensions': {'code': 'DOWNSTREAM_SERVICE_ERROR', 'serviceName': 'projectservice', 'query': 'query($id:UUID){project(id:$id){title id}}', 'variables': {'id': None}, 'exception': {'message': 'This project cannot be retrieved.', 'locations': [{'line': 1, 'column': 17}], 'path': ['project'], 'stacktrace': ['GraphQLError: This project cannot be retrieved.', '    at downstreamServiceError (/usr/src/app/node_modules/@apollo/gateway/dist/executeQueryPlan.js:268:12)', '    at /usr/src/app/node_modules/@apollo/gateway/dist/executeQueryPlan.js:168:57', '    at Array.map (<anonymous>)', '    at sendOperation (/usr/src/app/node_modules/@apollo/gateway/dist/executeQueryPlan.js:168:44)', '    at runMicrotasks (<anonymous>)', '    at processTicksAndRejections (internal/process/task_queues.js:97:5)', '    at async executeFetch (/usr/src/app/node_modules/@apollo/gateway/dist/executeQueryPlan.js:111:41)', '    at async executeNode (/usr/src/app/node_modules/@apollo/gateway/dist/executeQueryPlan.js:82:17)', '    at async Object.executeQueryPlan (/usr/src/app/node_modules/@apollo/gateway/dist/executeQueryPlan.js:22:27)', '    at async Object.ApolloGateway.executor (/usr/src/app/node_modules/@apollo/gateway/dist/index.js:100:30)']}}}
[ERROR] Something went wrong!
```

active pods:
```
platform-redis-ha-server-0                        2/2     Running            0          100m
frontend-http-7b5cf7cb9b-5pl25                    1/1     Running            0          100m
platform-postgresql-0                             1/1     Running            0          100m
gateway-6f8bd4688f-kzs9p                          2/2     Running            0          100m
platform-cloudserver-localdata-745965666b-prrtn   1/1     Running            0          100m
manifests-http-5cdc7985c9-xdhgp                   1/1     Running            0          100m
platform-rabbitmq-0                               1/1     Running            1          100m
projects-http-7fcbfbb47-xhbm9                     1/1     Running            0          100m
projects-admin-69c5f87b68-sjg27                   1/1     Running            0          100m
platform-cloudserver-56575659f5-65rfk             1/1     Running            1          100m
users-admin-c4f8484dc-khssf                       1/1     Running            4          100m
orgas-http-6c87c5f8cc-nsjdf                       1/1     Running            0          100m
orgas-admin-dd475fd6f-wgkd4                       1/1     Running            0          100m
platform-mongodb-replicaset-0                     1/1     Running            0          100m
users-http-6df5d97f9f-2zhns                       1/1     Running            4          100m
platform-keycloak-0                               1/1     Running            0          100m
apollo-5b796d569f-vbgjr                           1/1     Running            5          100m
keycloak-startup-494h8                            1/1     Running            0          92m
users-amqp-consumer-5d49c985f7-hxjg6              0/1     CrashLoopBackOff   23         100m
```

**Comment by Schille** [comment] 2021-06-14 15:48
I tried it myself and found it working
```
 mschilonka@thinkpad-x1:~/workspace/unikube/projects$ unikube project down
[?] Please select a project: Unikube Platform
 > Unikube Platform

[INFO] Stopping Kubernetes cluster for 'Unikube Platform'

[SUCCESS] The project cluster is down.
```
This might be a temporary issue?

**Comment by vvvityaaa** [comment] 2021-06-17 17:34
Was not able to reproduce this error, so I closed this issue.

**Closed** 2021-06-17 17:33 UTC
Labels: bug
